# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'cv.tex'
      - '.github/workflows/blank.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cv.tex'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          
      - name: Copy file
        run: |
          ls -a
          mkdir -p docs
          ls -a
          sudo mv cv.pdf docs
          ls -a
          
      - name: Commit pdf
        run: |
          git config --global user.name 'Nikita Rusetskii'
          git config --global user.email 'rusetscky@outlook.com'
          git commit -am "push cv"
          git push
